#!/usr/bin/env python3
"""Codex-driven long-running harness generator for DL research projects.

Generation strategy:
1. Run one Codex analysis pass to produce planning metadata
   (summary, required_files, feature_list, task_plan).
2. Generate scaffold files with one Codex call per file, instead of one giant
   bundle response containing all file contents.
3. Validate outputs and materialize files under .codex-research/.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple


CORE_REQUIRED_PATHS = [
    ".codex-research/research_spec.md",
    ".codex-research/feature_list.json",
    ".codex-research/task_plan.json",
    ".codex-research/required_files.json",
    ".codex-research/session_progress.md",
    ".codex-research/decision_log.md",
    ".codex-research/run_registry.jsonl",
    ".codex-research/init.sh",
    ".codex-research/checks/smoke_test.sh",
    ".codex-research/prompts/initializer.md",
    ".codex-research/prompts/worker.md",
    ".codex-research/workflow/CODEX.md",
    ".codex-research/run_one_task.sh",
    ".codex-research/run_plan.sh",
    ".codex-research/MECHANISM.md",
]

DEFAULT_REASON = "Generated by Codex from the uploaded research plan."

META_JSON_PATHS = {
    ".codex-research/feature_list.json",
    ".codex-research/task_plan.json",
    ".codex-research/required_files.json",
}


def iso_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def as_json_pretty(data: object) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def ensure_codex_cli() -> None:
    if shutil.which("codex") is None:
        raise SystemExit("codex CLI is not available in PATH")


def normalize_rel_path(path: str) -> str:
    normalized = path.strip().replace("\\", "/")
    if not normalized.startswith(".codex-research/"):
        raise SystemExit(f"generated path must be under .codex-research/: {path}")
    parts = Path(normalized).parts
    if ".." in parts:
        raise SystemExit(f"generated path must not contain '..': {path}")
    return normalized


def try_normalize_rel_path(path: str) -> Optional[str]:
    normalized = path.strip().replace("\\", "/")
    if not normalized.startswith(".codex-research/"):
        return None
    parts = Path(normalized).parts
    if ".." in parts:
        return None
    return normalized


def _analysis_schema() -> Dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["summary", "required_files", "feature_list", "task_plan"],
        "properties": {
            "summary": {"type": "string", "minLength": 20},
            "required_files": {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["path", "reason"],
                    "properties": {
                        "path": {"type": "string", "minLength": 5},
                        "reason": {"type": "string", "minLength": 3},
                    },
                },
            },
            "feature_list": {
                "type": "array",
                "minItems": 1,
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["id", "category", "description", "steps", "passes"],
                    "properties": {
                        "id": {"type": "string", "minLength": 2},
                        "category": {"type": "string", "minLength": 2},
                        "description": {"type": "string", "minLength": 5},
                        "steps": {
                            "type": "array",
                            "minItems": 1,
                            "items": {"type": "string", "minLength": 2},
                        },
                        "passes": {"type": "boolean"},
                    },
                },
            },
            "task_plan": {
                "type": "object",
                "additionalProperties": False,
                "required": ["project", "rules", "tasks"],
                "properties": {
                    "project": {"type": "string", "minLength": 1},
                    "rules": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"type": "string", "minLength": 3},
                    },
                    "tasks": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "object",
                            "additionalProperties": False,
                            "required": ["id", "title", "description", "steps", "passes"],
                            "properties": {
                                "id": {"type": "string", "minLength": 2},
                                "title": {"type": "string", "minLength": 3},
                                "description": {"type": "string", "minLength": 5},
                                "steps": {
                                    "type": "array",
                                    "minItems": 1,
                                    "items": {"type": "string", "minLength": 2},
                                },
                                "passes": {"type": "boolean"},
                            },
                        },
                    },
                },
            },
        },
    }


def _single_file_schema(target_path: str) -> Dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["path", "content", "reason", "executable"],
        "properties": {
            "path": {"type": "string", "const": target_path},
            "content": {"type": "string"},
            "reason": {"type": "string", "minLength": 3},
            "executable": {"type": "boolean"},
        },
    }


def _log_paths(target_root: Path, tag: str) -> Tuple[Path, Path, Path]:
    log_root = target_root / ".codex-research" / "plan" / "codex_generation_logs"
    log_root.mkdir(parents=True, exist_ok=True)

    safe_tag = re.sub(r"[^a-zA-Z0-9_.-]+", "_", tag)[:120] or "codex"
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d_%H%M%S_%f")

    schema_path = log_root / f"{stamp}_{safe_tag}.schema.json"
    output_path = log_root / f"{stamp}_{safe_tag}.output.json"
    log_path = log_root / f"{stamp}_{safe_tag}.exec.log"
    return schema_path, output_path, log_path


def _run_codex_json(
    *,
    prompt: str,
    schema: Dict[str, Any],
    target_root: Path,
    model: str,
    tag: str,
) -> Dict[str, Any]:
    ensure_codex_cli()
    schema_path, output_path, log_path = _log_paths(target_root, tag)
    schema_path.write_text(as_json_pretty(schema), encoding="utf-8")

    cmd: List[str] = [
        "codex",
        "exec",
        "--skip-git-repo-check",
        "--ephemeral",
        "--dangerously-bypass-approvals-and-sandbox",
        "-C",
        str(target_root),
        "--output-schema",
        str(schema_path),
        "--output-last-message",
        str(output_path),
        "-",
    ]
    if model:
        cmd.extend(["--model", model])

    proc = subprocess.run(
        cmd,
        input=prompt,
        text=True,
        capture_output=True,
        check=False,
    )

    log_path.write_text(
        "CMD\n"
        + " ".join(cmd)
        + "\n\nSTDOUT\n"
        + proc.stdout
        + "\n\nSTDERR\n"
        + proc.stderr
        + "\n",
        encoding="utf-8",
    )

    if proc.returncode != 0:
        raise SystemExit(
            "codex generation failed "
            f"(exit={proc.returncode}, tag={tag}). See log: {log_path}"
        )

    if not output_path.exists():
        raise SystemExit(
            f"codex generation produced no output JSON (tag={tag}). Log: {log_path}"
        )

    try:
        return json.loads(output_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(
            f"failed to parse codex JSON output (tag={tag}): {output_path}: {exc}"
        ) from exc


def _build_analysis_prompt(plan_path: Path, plan_text: str) -> str:
    required_paths_block = "\n".join(f"- {path}" for path in CORE_REQUIRED_PATHS)
    return f"""You are generating planning metadata for a Codex long-running deep-learning harness.

Goal:
Produce project-aware scaffolding metadata from the provided plan.

Critical requirement:
Do NOT use simplistic keyword-only extraction logic. Infer concrete workflow details from full plan context,
including metrics, runtime environment, scheduler usage (e.g., Slurm), validation strategy, and reproducibility.

Return JSON only.

Hard rules:
1. required_files must include all mandatory core paths listed below.
2. You may add extra .codex-research paths when needed by the plan.
3. feature_list and task_plan.tasks must start with passes=false.
4. Keep paths strictly under .codex-research/.
5. Include realistic and actionable descriptions/steps.

Mandatory core paths:
{required_paths_block}

Source plan path: {plan_path.resolve()}
SOURCE_PLAN_START
{plan_text}
SOURCE_PLAN_END
"""


def _build_file_prompt(
    *,
    plan_path: Path,
    plan_text: str,
    summary: str,
    required_files: List[Dict[str, str]],
    feature_list: List[Dict[str, Any]],
    task_plan: Dict[str, Any],
    target_path: str,
    reason: str,
    index: int,
    total: int,
) -> str:
    required_block = "\n".join(f"- {item['path']}: {item['reason']}" for item in required_files)
    feature_block = as_json_pretty(feature_list)
    task_block = as_json_pretty(task_plan)

    return f"""You are generating one file for a Codex DL harness.

Return JSON only.

Generation progress: file {index} of {total}
Target path (must match exactly): {target_path}
Target reason: {reason}

Global constraints:
1. Do NOT use simplistic keyword-only logic.
2. Use full plan context to reflect realistic metric/environment/slurm/eval workflow where relevant.
3. Keep content production-ready and consistent with feature/task plans below.
4. Do not include markdown code fences around file content.
5. Keep path exactly as target path.

Harness summary:
{summary}

Required files list:
{required_block}

Feature list JSON:
{feature_block}

Task plan JSON:
{task_block}

Source plan path: {plan_path.resolve()}
SOURCE_PLAN_START
{plan_text}
SOURCE_PLAN_END
"""


def _normalize_feature_list(raw: Any) -> List[Dict[str, Any]]:
    if not isinstance(raw, list):
        raise SystemExit("feature_list must be a JSON list")

    items: List[Dict[str, Any]] = []
    for idx, entry in enumerate(raw, start=1):
        if not isinstance(entry, dict):
            raise SystemExit(f"feature_list[{idx}] must be an object")

        item = {
            "id": str(entry.get("id", f"F-{idx:04d}")).strip() or f"F-{idx:04d}",
            "category": str(entry.get("category", "research")).strip() or "research",
            "description": str(entry.get("description", "")).strip(),
            "steps": entry.get("steps", []),
            "passes": False,
        }
        if not item["description"]:
            raise SystemExit(f"feature_list[{idx}].description is empty")
        if not isinstance(item["steps"], list) or not item["steps"]:
            raise SystemExit(f"feature_list[{idx}].steps must be a non-empty list")

        item["steps"] = [str(step).strip() for step in item["steps"] if str(step).strip()]
        if not item["steps"]:
            raise SystemExit(f"feature_list[{idx}].steps resolved to empty list")

        items.append(item)
    return items


def _normalize_task_plan(raw: Any, plan_path: Path, generated_at: str) -> Dict[str, Any]:
    if not isinstance(raw, dict):
        raise SystemExit("task_plan must be a JSON object")

    tasks = raw.get("tasks")
    if not isinstance(tasks, list) or not tasks:
        raise SystemExit("task_plan.tasks must be a non-empty list")

    normalized_tasks: List[Dict[str, Any]] = []
    for idx, entry in enumerate(tasks, start=1):
        if not isinstance(entry, dict):
            raise SystemExit(f"task_plan.tasks[{idx}] must be an object")

        task = {
            "id": str(entry.get("id", f"T-{idx:04d}")).strip() or f"T-{idx:04d}",
            "title": str(entry.get("title", "")).strip(),
            "description": str(entry.get("description", "")).strip(),
            "steps": entry.get("steps", []),
            "passes": False,
        }
        if not task["title"]:
            raise SystemExit(f"task_plan.tasks[{idx}].title is empty")
        if not task["description"]:
            raise SystemExit(f"task_plan.tasks[{idx}].description is empty")
        if not isinstance(task["steps"], list) or not task["steps"]:
            raise SystemExit(f"task_plan.tasks[{idx}].steps must be a non-empty list")

        task["steps"] = [str(step).strip() for step in task["steps"] if str(step).strip()]
        if not task["steps"]:
            raise SystemExit(f"task_plan.tasks[{idx}].steps resolved to empty list")

        normalized_tasks.append(task)

    rules = raw.get("rules")
    if not isinstance(rules, list) or not rules:
        rules = [
            "Exactly one task per Codex session.",
            "Do not set passes=true without test/command evidence.",
            "If blocked, keep passes=false and log blocker details.",
        ]

    return {
        "project": str(raw.get("project", plan_path.stem)).strip() or plan_path.stem,
        "generated_at": generated_at,
        "plan_path": str(plan_path.resolve()),
        "rules": [str(rule).strip() for rule in rules if str(rule).strip()],
        "tasks": normalized_tasks,
    }


def _ensure_text_with_newline(value: str) -> str:
    return value if value.endswith("\n") else value + "\n"


def _run_codex_analysis(plan_path: Path, target_root: Path, model: str) -> Dict[str, Any]:
    plan_text = read_text(plan_path)
    prompt = _build_analysis_prompt(plan_path, plan_text)
    return _run_codex_json(
        prompt=prompt,
        schema=_analysis_schema(),
        target_root=target_root,
        model=model,
        tag="analysis",
    )


def _normalize_analysis(raw_analysis: Dict[str, Any], plan_path: Path) -> Dict[str, Any]:
    generated_at = iso_now()

    summary = str(raw_analysis.get("summary", "")).strip()
    if len(summary) < 20:
        raise SystemExit("codex summary is too short; expected detailed generation summary")

    feature_list = _normalize_feature_list(raw_analysis.get("feature_list"))
    task_plan = _normalize_task_plan(raw_analysis.get("task_plan"), plan_path, generated_at)

    required_map: Dict[str, str] = {}
    skipped_paths: Set[str] = set()

    raw_required = raw_analysis.get("required_files")
    if not isinstance(raw_required, list) or not raw_required:
        raise SystemExit("required_files must be a non-empty list")

    for idx, entry in enumerate(raw_required, start=1):
        if not isinstance(entry, dict):
            raise SystemExit(f"required_files[{idx}] must be an object")
        raw_path = str(entry.get("path", ""))
        path = try_normalize_rel_path(raw_path)
        if path is None:
            skipped_paths.add(raw_path or "<empty>")
            continue
        reason = str(entry.get("reason", "")).strip() or DEFAULT_REASON
        required_map[path] = reason

    for path in CORE_REQUIRED_PATHS:
        required_map.setdefault(path, DEFAULT_REASON)

    required_files = [
        {"path": path, "reason": required_map[path]}
        for path in sorted(required_map.keys())
    ]

    if skipped_paths:
        skipped_preview = ", ".join(sorted(skipped_paths)[:12])
        if len(skipped_paths) > 12:
            skipped_preview += ", ..."
        print(
            "[warn] ignored required paths outside .codex-research/: "
            f"{skipped_preview}"
        )

    return {
        "generated_at": generated_at,
        "plan_path": str(plan_path.resolve()),
        "source": "codex",
        "summary": summary,
        "required_files": required_files,
        "feature_list": feature_list,
        "task_plan": task_plan,
    }


def _run_codex_single_file(
    *,
    plan_path: Path,
    target_root: Path,
    model: str,
    analysis: Dict[str, Any],
    target_path: str,
    reason: str,
    index: int,
    total: int,
) -> Dict[str, Any]:
    plan_text = read_text(plan_path)
    prompt = _build_file_prompt(
        plan_path=plan_path,
        plan_text=plan_text,
        summary=analysis["summary"],
        required_files=analysis["required_files"],
        feature_list=analysis["feature_list"],
        task_plan=analysis["task_plan"],
        target_path=target_path,
        reason=reason,
        index=index,
        total=total,
    )
    tag = f"file_{index:03d}_{target_path}"
    result = _run_codex_json(
        prompt=prompt,
        schema=_single_file_schema(target_path),
        target_root=target_root,
        model=model,
        tag=tag,
    )

    path = normalize_rel_path(str(result.get("path", "")))
    if path != target_path:
        raise SystemExit(f"single-file codex output path mismatch: expected {target_path}, got {path}")

    content = result.get("content")
    if not isinstance(content, str):
        raise SystemExit(f"single-file codex output content must be string: {target_path}")

    gen_reason = str(result.get("reason", "")).strip() or reason or DEFAULT_REASON
    executable = bool(result.get("executable", False))

    return {
        "path": target_path,
        "content": _ensure_text_with_newline(content),
        "reason": gen_reason,
        "executable": executable,
    }


def _materialize_generated_bundle(
    *,
    plan_path: Path,
    target_root: Path,
    model: str,
    analysis: Dict[str, Any],
) -> Dict[str, Any]:
    required_map = {item["path"]: item["reason"] for item in analysis["required_files"]}
    required_paths = sorted(required_map.keys())

    file_map: Dict[str, str] = {}
    executable_paths: Set[str] = set()

    # Deterministic JSON artifacts from analysis stage.
    file_map[".codex-research/feature_list.json"] = as_json_pretty(analysis["feature_list"])
    file_map[".codex-research/task_plan.json"] = as_json_pretty(analysis["task_plan"])

    generated_count = 0
    codex_targets: List[str] = [p for p in required_paths if p not in META_JSON_PATHS]
    total_targets = len(codex_targets)

    for rel_path in codex_targets:
        generated_count += 1
        entry = _run_codex_single_file(
            plan_path=plan_path,
            target_root=target_root,
            model=model,
            analysis=analysis,
            target_path=rel_path,
            reason=required_map.get(rel_path, DEFAULT_REASON),
            index=generated_count,
            total=total_targets,
        )
        file_map[rel_path] = entry["content"]
        required_map[rel_path] = entry["reason"]
        if entry["executable"] or rel_path.endswith((".sh", ".sbatch")):
            executable_paths.add(rel_path)

    for path in CORE_REQUIRED_PATHS:
        required_map.setdefault(path, DEFAULT_REASON)

    for path in list(file_map):
        required_map.setdefault(path, DEFAULT_REASON)

    required_files = [
        {"path": path, "reason": required_map[path]}
        for path in sorted(required_map.keys())
    ]

    required_payload = {
        "generated_at": analysis["generated_at"],
        "plan_path": analysis["plan_path"],
        "source": "codex",
        "summary": analysis["summary"],
        "required_files": required_files,
    }
    file_map[".codex-research/required_files.json"] = as_json_pretty(required_payload)

    missing_core = [path for path in CORE_REQUIRED_PATHS if path not in file_map]
    if missing_core:
        raise SystemExit("generated files missing core paths: " + ", ".join(missing_core))

    return {
        "generated_at": analysis["generated_at"],
        "plan_path": analysis["plan_path"],
        "source": "codex",
        "summary": analysis["summary"],
        "required_files": required_files,
        "feature_list": analysis["feature_list"],
        "task_plan": analysis["task_plan"],
        "file_map": file_map,
        "executable_paths": sorted(executable_paths),
    }


def load_bundle(plan_path: Path, target_root: Path, codex_model: str) -> Dict[str, Any]:
    raw_analysis = _run_codex_analysis(plan_path=plan_path, target_root=target_root, model=codex_model)
    analysis = _normalize_analysis(raw_analysis, plan_path=plan_path)
    return _materialize_generated_bundle(
        plan_path=plan_path,
        target_root=target_root,
        model=codex_model,
        analysis=analysis,
    )


def load_analysis(plan_path: Path, target_root: Path, codex_model: str) -> Dict[str, Any]:
    raw_analysis = _run_codex_analysis(plan_path=plan_path, target_root=target_root, model=codex_model)
    return _normalize_analysis(raw_analysis, plan_path=plan_path)


def write_file(path: Path, content: str, force: bool) -> Tuple[bool, str]:
    if path.exists() and not force:
        return False, "exists"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True, "written"


def chmod_if_shell(path: Path) -> None:
    if path.suffix in {".sh", ".sbatch"}:
        current = path.stat().st_mode
        path.chmod(current | 0o111)


def cmd_extract(args: argparse.Namespace) -> int:
    plan_path = Path(args.plan).resolve()
    target_root = Path(args.target).resolve() if args.target else plan_path.parent
    out_path = Path(args.out).resolve()

    analysis = load_analysis(plan_path=plan_path, target_root=target_root, codex_model=args.codex_model)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        as_json_pretty(
            {
                "generated_at": analysis["generated_at"],
                "plan_path": analysis["plan_path"],
                "source": analysis["source"],
                "summary": analysis["summary"],
                "required_files": analysis["required_files"],
                "feature_list": analysis["feature_list"],
                "task_plan": analysis["task_plan"],
            }
        ),
        encoding="utf-8",
    )
    print(f"[extract] wrote {out_path}")
    return 0


def bootstrap_from_bundle(
    target_root: Path,
    bundle: Dict[str, Any],
    force: bool,
) -> Tuple[int, int]:
    file_map: Dict[str, str] = bundle["file_map"]
    executable_paths: Set[str] = set(bundle["executable_paths"])

    created = 0
    skipped = 0

    for rel_path in sorted(file_map.keys()):
        abs_path = target_root / rel_path
        content = file_map[rel_path]
        wrote, status = write_file(abs_path, content, force)
        if wrote:
            if rel_path in executable_paths or abs_path.suffix in {".sh", ".sbatch"}:
                chmod_if_shell(abs_path)
            created += 1
            print(f"[bootstrap] created {abs_path}")
        else:
            skipped += 1
            print(f"[bootstrap] skipped {abs_path} ({status})")

    return created, skipped


def cmd_bootstrap(args: argparse.Namespace) -> int:
    plan_path = Path(args.plan).resolve()
    target_root = Path(args.target).resolve()
    bundle = load_bundle(plan_path=plan_path, target_root=target_root, codex_model=args.codex_model)

    created, skipped = bootstrap_from_bundle(target_root, bundle, args.force)
    print(f"[bootstrap] done: created={created}, skipped={skipped}")
    return 0


def cmd_gen_doc(args: argparse.Namespace) -> int:
    plan_path = Path(args.plan).resolve()
    target_root = Path(args.target).resolve()
    analysis = load_analysis(plan_path=plan_path, target_root=target_root, codex_model=args.codex_model)

    # Only one file generation call for gen-doc mode.
    mechanism_entry = _run_codex_single_file(
        plan_path=plan_path,
        target_root=target_root,
        model=args.codex_model,
        analysis=analysis,
        target_path=".codex-research/MECHANISM.md",
        reason="In-project mechanism introduction document.",
        index=1,
        total=1,
    )

    mechanism_path = target_root / mechanism_entry["path"]
    mechanism_path.parent.mkdir(parents=True, exist_ok=True)
    mechanism_path.write_text(mechanism_entry["content"], encoding="utf-8")
    print(f"[doc] wrote {mechanism_path}")
    return 0


def cmd_all(args: argparse.Namespace) -> int:
    plan_path = Path(args.plan).resolve()
    target_root = Path(args.target).resolve()
    bundle = load_bundle(plan_path=plan_path, target_root=target_root, codex_model=args.codex_model)

    extract_path = target_root / ".codex-research/required_files.generated.json"
    extract_path.parent.mkdir(parents=True, exist_ok=True)
    extract_path.write_text(
        as_json_pretty(
            {
                "generated_at": bundle["generated_at"],
                "plan_path": bundle["plan_path"],
                "source": bundle["source"],
                "summary": bundle["summary"],
                "required_files": bundle["required_files"],
                "feature_list": bundle["feature_list"],
                "task_plan": bundle["task_plan"],
            }
        ),
        encoding="utf-8",
    )

    created, skipped = bootstrap_from_bundle(target_root, bundle, args.force)

    mechanism_path = target_root / ".codex-research/MECHANISM.md"
    print(f"[all] wrote manifest: {extract_path}")
    print(f"[all] wrote mechanism: {mechanism_path}")
    print(f"[all] done: created={created}, skipped={skipped}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Codex-driven long-running harness bootstrapper for DL research.",
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    extract = sub.add_parser("extract", help="Generate Codex-derived manifest from a plan")
    extract.add_argument("--plan", required=True, help="Path to uploaded plan file")
    extract.add_argument("--out", required=True, help="Output JSON path")
    extract.add_argument(
        "--target",
        required=False,
        help="Optional target project root for Codex execution context",
    )
    extract.add_argument("--codex-model", default="", help="Optional Codex model override")
    extract.set_defaults(func=cmd_extract)

    bootstrap = sub.add_parser("bootstrap", help="Create harness files in target project")
    bootstrap.add_argument("--plan", required=True, help="Path to uploaded plan file")
    bootstrap.add_argument("--target", required=True, help="Target project root")
    bootstrap.add_argument("--force", action="store_true", help="Overwrite existing files")
    bootstrap.add_argument("--codex-model", default="", help="Optional Codex model override")
    bootstrap.set_defaults(func=cmd_bootstrap)

    gen_doc = sub.add_parser("gen-doc", help="Generate mechanism markdown in project")
    gen_doc.add_argument("--plan", required=True, help="Path to uploaded plan file")
    gen_doc.add_argument("--target", required=True, help="Target project root")
    gen_doc.add_argument("--codex-model", default="", help="Optional Codex model override")
    gen_doc.set_defaults(func=cmd_gen_doc)

    all_cmd = sub.add_parser("all", help="Extract + bootstrap + generate doc")
    all_cmd.add_argument("--plan", required=True, help="Path to uploaded plan file")
    all_cmd.add_argument("--target", required=True, help="Target project root")
    all_cmd.add_argument("--force", action="store_true", help="Overwrite existing files")
    all_cmd.add_argument("--codex-model", default="", help="Optional Codex model override")
    all_cmd.set_defaults(func=cmd_all)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    plan_path = Path(getattr(args, "plan", ""))
    if plan_path and not plan_path.exists():
        raise SystemExit(f"Plan file not found: {plan_path}")

    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
